# Generated by Django 4.0.1 on 2022-03-28 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line', to='store.order'),
        ),
    ]
