# Generated by Django 4.0.1 on 2022-05-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_total_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
