# Generated by Django 4.0.1 on 2022-03-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
