# Generated by Django 4.0.1 on 2022-03-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
